### ISSUE TITLE
About  Evaluation Metric

### ISSUE THREAD

**Issue by Bahuia** [StevenWD/HR-BiLSTM#3]
Hi, steven
I try your implementation, but the accuracy is far better than the paper. It seemed that your evaluation metrics are different. Do you know how the accuracy of the original paper is calculated? Thank you!

**Comment by StevenWD** [comment]
I have updated my evaluation code with the metrics mentioned in the paper.

**Comment by Bahuia** [comment]
Have you ever managed to get accuracy above 81%？

**Comment by StevenWD** [comment]
I got 82% accuracy with my code.

**Comment by Bahuia** [comment]
Are the hyper parameters set as the uploaded code ? There is an error at line 267. Should I replace "all_word_embedding" with "glove_embedding" ? Thank you!

**Comment by StevenWD** [comment]
I have fixed this bug, the variable name is misused. Sorry for this mistake.
